## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux
  - osx
  
julia:
  - 1.0
  - 1.1
  - nightly
  
matrix:
  allow_failures:
    - os: osx
    - julia: nightly

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
    
jobs:
  include:
    - stage: Documentation
      julia: 1.1
      os: linux
      script:
        - julia --project=docs -e 'using Pkg; Pkg.instantiate(); Pkg.develop(PackageSpec(path=pwd()))'
        - julia --project=docs --color=yes docs/make.jl
      after_success: skip

notifications:
  email: true

git:
  depth: 99999999

